language: java
jdk: openjdk11
sudo: required

script:
  - ./gradlew build

services:
  - docker
  - postgresql

after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/