server.port: 5849

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
    hibernate:
      ddl-auto: validate
  datasource.url: jdbc:postgresql://localhost:5432/rapio
  datasource.username: postgres

  liquibase:
    enabled: false
  jackson.deserialization.read-unknown-enum-values-using-default-value: true



server:
  servlet:
    session:
      persistent: false
      timeout: 0


hedvig:
  api-gateway:
    url: api-gateway
    token: test