server.port: 5849

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/rapio
    username: postgres
    password: hedvig
    platform: POSTGRESQL
