package com.hedvig.rapio.apikeys

enum class Partner(val role: Role) {
    INSPLANET(role = Role.COMPARISON),
    COMPRICER(role = Role.COMPARISON),
    HEDVIG(role = Role.COMPARISON),
    INSURLEY(role = Role.COMPARISON),
    KEYSOLUTIONS(role = Role.COMPARISON),
    SPIFF(role = Role.COMPARISON),
    TJENSTETORGET(role = Role.COMPARISON),
    AVY(role = Role.DISTRIBUTION),
    FORSIKRINGSPORTALEN(role = Role.COMPARISON),
    SAMLINO(role = Role.COMPARISON),
    FINDFORSIKRING(role = Role.COMPARISON),
    FORSIKRINGSGUIDEN(role = Role.COMPARISON),
    KEY_HOLE(role = Role.COMPARISON),
    COPENHAGEN_SALES(role = Role.COMPARISON),
    CHARLIE(role = Role.COMPARISON),
    FLYTTSMART(role = Role.COMPARISON),
    PAMIND(role = Role.COMPARISON),
    MECENAT(role = Role.COMPARISON),
    HAPPENS(role = Role.COMPARISON),
    HEMAVI(role = Role.COMPARISON),
    SAMBLA(role = Role.COMPARISON),
    PEACH(role = Role.COMPARISON),
    MMG(role = Role.COMPARISON),
}
